spring:
  application:
    name: spring-amqp-with-protobuf-testing
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    virtual-host: /
audit:
  amqp:
    queue:
      auditMessageNorth: north_messages_queue
      auditMessageSouth: south_messages_queue
